import React from "react";
import { BlogItemType } from "../homepageuitils/Blog";
import { v4 as uuidv4 } from "uuid";
import Pagination from "../../uitils/Pagination";
import { useRecoilValue } from "recoil";
import { SelectedLanguageState } from "../header/SelectedLanguage";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import { Baseurl } from "../../api/Baseurl";

export const BlogItems: BlogItemType[] = [
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
    slug: "sdflkdsfpodkskpwoefpwoekfpoewk",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
  {
    id: uuidv4(),
    image: "../blogimage.svg",
    author: "Gülay Əsgərli",
    time: "Mart 11, 2024",
    category: "Blog & Yeniliklər",
    blogdescription: "Lorem ipsum dolor sit amet consectetur. Sed amet pulvinar cursus volutpat dolor.",
    blogtitle: "Jurnal mebeli seçimi zamanı nəyə diqqət edilməlidir?",
  },
];
const Blogs: React.FC = () => {
  const activeLanguage = useRecoilValue(SelectedLanguageState);

  //Fetch blogs
  const { data: BlogData } = useQuery({
    queryKey: ["blogDataKey", activeLanguage],
    queryFn: async () => {
      const response = await axios.get(`${Baseurl}/blogs`, {
        headers: {
          "Accept-Language": activeLanguage,
        },
      });
      return response.data?.blogs;
    },
    staleTime: 1000000,
  });

  return (
    <div className="blogs">
      <Pagination data={BlogData && BlogData.length > 0 ? BlogData : ""} itemsPerPage={16} />
    </div>
  );
};

export default Blogs;
